"""
Build-time helpers for custom DC configuration.

Reads the DC config endpoint URL from blah-server.config.url (placed next to
the main app config), fetches the configuration at build time, and writes a
Swift source file with literal CustomDCConfig struct values so that the runtime
incurs zero parsing overhead.

To change the endpoint, edit blah-server.config.url — do not hardcode the URL
in this script.
"""

import json
import os
import urllib.request


# ---------------------------------------------------------------------------
# Swift codegen
# ---------------------------------------------------------------------------

def _swift_string_literal(s):
    """Emit s as a Swift multi-line string literal (triple-quoted)."""
    return '"""\n{}\n"""'.format(s)


def _dc_literal(dc):
    """
    Generate a Swift .init(...) literal for one DC from the API response.

    API shape:
      {
        "id": 2,
        "rsaPublicKey": "-----BEGIN RSA PUBLIC KEY-----\\n...\\n-----END RSA PUBLIC KEY-----",
        "endpoints": [{"ip": "...", "port": ..., "wsTlsOnly": false}, ...],
        ...
      }
    """
    endpoints = ', '.join(
        '("{}", {})'.format(ep['ip'], ep['port'])
        for ep in dc.get('endpoints', [])
        if not ep.get('wsTlsOnly', False)
    )
    pem = dc['rsaPublicKey'].strip()
    return (
        '        .init(\n'
        '            id: {},\n'
        '            endpoints: [{}],\n'
        '            rsaPublicKeyPem: {}\n'
        '        )'
    ).format(dc['id'], endpoints, _swift_string_literal(pem))


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def generate_custom_dc_config_swift(main_config_path, output_path):
    """
    Look for blah-server.config.url next to main_config_path.
    Fetch the DC list from that URL and write a Swift file at output_path
    containing a CustomDCConfig literal (or nil when the URL file is absent).
    """
    dir_path = os.path.dirname(os.path.abspath(main_config_path))
    url_config_path = os.path.join(dir_path, 'blah-server.config.url')

    header = '// Auto-generated by CustomDCConfigBuild.py — do not edit.\n'

    if not os.path.exists(url_config_path):
        content = header + 'let _customDCConfigData: CustomDCConfig? = nil\n'
    else:
        url = open(url_config_path).read().strip()
        try:
            req = urllib.request.Request(url, headers={
                'Accept': 'application/json',
                'User-Agent': 'TBlah-iOS-BuildSystem/1.0',
            })
            with urllib.request.urlopen(req, timeout=15) as response:
                config = json.loads(response.read().decode('utf-8'))
        except Exception as e:
            raise RuntimeError('Failed to fetch DC config from {}: {}'.format(url, e))

        dcs = config.get('dcs', [])
        if not dcs:
            raise RuntimeError('DC config response from {} contained no DCs'.format(url))

        default_dc_id = dcs[0]['id']
        dc_literals = ',\n'.join(_dc_literal(dc) for dc in dcs)
        content = (
            header +
            'let _customDCConfigData: CustomDCConfig? = CustomDCConfig(\n'
            '    defaultDcId: {},\n'
            '    dcs: [\n'
            '{}\n'
            '    ]\n'
            ')\n'
        ).format(default_dc_id, dc_literals)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(content)
