"""
Build-time helpers for custom DC configuration (blah-server.config.json).

Reads blah-server.config.json next to the main app config, converts RSA keys
from (nHex, e) to PKCS#1 PEM, and writes a Swift source file with literal
CustomDCConfig struct values so that the runtime incurs zero parsing overhead.
"""

import base64
import json
import os


# ---------------------------------------------------------------------------
# RSA PKCS#1 PEM helpers
# ---------------------------------------------------------------------------

def _asn1_length(n):
    if n < 0x80:
        return bytes([n])
    elif n < 0x100:
        return bytes([0x81, n])
    else:
        return bytes([0x82, (n >> 8) & 0xff, n & 0xff])


def _asn1_integer(val_bytes):
    if val_bytes[0] & 0x80:
        val_bytes = b'\x00' + val_bytes
    return b'\x02' + _asn1_length(len(val_bytes)) + val_bytes


def _n_e_to_pkcs1_pem(n_hex, e):
    """Convert RSA public key (n as hex string, e as int) to PKCS#1 PEM."""
    n_bytes = bytes.fromhex(n_hex)
    e_int = int(e)
    e_bytes = e_int.to_bytes((e_int.bit_length() + 7) // 8, 'big')
    content = _asn1_integer(n_bytes) + _asn1_integer(e_bytes)
    seq = b'\x30' + _asn1_length(len(content)) + content
    b64 = base64.b64encode(seq).decode('ascii')
    lines = '\n'.join(b64[i:i + 64] for i in range(0, len(b64), 64))
    return '-----BEGIN RSA PUBLIC KEY-----\n{}\n-----END RSA PUBLIC KEY-----'.format(lines)


# ---------------------------------------------------------------------------
# Swift codegen
# ---------------------------------------------------------------------------

def _swift_string_literal(s):
    """Emit s as a Swift multi-line string literal (triple-quoted)."""
    return '"""\n{}\n"""'.format(s)


def _dc_literal(dc):
    endpoints = ', '.join(
        '("{}", {})'.format(ep['ip'], ep['port'])
        for ep in dc.get('endpoints', [])
        if not ep.get('wssOnly', False)
    )
    pem = _n_e_to_pkcs1_pem(dc['rsaKey']['nHex'], dc['rsaKey']['e'])
    return (
        '        .init(\n'
        '            id: {},\n'
        '            endpoints: [{}],\n'
        '            rsaPublicKeyPem: {}\n'
        '        )'
    ).format(dc['id'], endpoints, _swift_string_literal(pem))


def generate_custom_dc_config_swift(main_config_path, output_path):
    """
    Look for blah-server.config.json next to main_config_path.
    Write a Swift file at output_path containing a CustomDCConfig literal
    (or nil when the server config is absent).
    """
    dir_path = os.path.dirname(os.path.abspath(main_config_path))
    server_config_path = os.path.join(dir_path, 'blah-server.config.json')

    header = '// Auto-generated by CustomDCConfigBuild.py — do not edit.\n'

    if not os.path.exists(server_config_path):
        content = header + 'let _customDCConfigData: CustomDCConfig? = nil\n'
    else:
        with open(server_config_path) as f:
            config = json.load(f)

        dc_literals = ',\n'.join(_dc_literal(dc) for dc in config.get('dcs', []))
        content = (
            header +
            'let _customDCConfigData: CustomDCConfig? = CustomDCConfig(\n'
            '    defaultDcId: {},\n'
            '    dcs: [\n'
            '{}\n'
            '    ]\n'
            ')\n'
        ).format(config['defaultDcId'], dc_literals)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(content)
