objc_library(
    name = "BlahBranding",
    enable_modules = True,
    module_name = "BlahBranding",
    srcs = ["Sources/BlahBranding.m"],
    hdrs = ["PublicHeaders/BlahBranding/BlahBranding.h"],
    includes = ["PublicHeaders"],
    sdk_frameworks = ["Foundation"],
    visibility = ["//visibility:public"],
)
